Numerical computing with Python
===============================

Disclaimer
----------
I've put a lot of work into planning this class, but I don't really have experience teaching more than one person at a time. There are going to be some rough edges. I'll really appreciate your help during and between classes letting me know if it's too fast, too slow, what works, and what doesn't.

Learning Goals
--------------
There are three different kinds of ways that people can interact with programs. Excel and GraphPad use graphical user interfaces (GUIs), which are all the point-and-click stuff. Our goal today is to understand how to interface with tools in Python. These aren't point-and-click: they use an application programming interface (API).

The power of Python comes from packages. There's the central language, which is also called the standard library, and then packages. So for example, if I want to make plots, I will need to import a package called `matplotlib`. Some of you only want to learn Python becaause it's the way to interact with these packages, so today, our goal is to cover just enough Python so you can do that.

We're going to do an intro `numpy` for core aspects of scientific computing; NumPy is like MATLAB or R or a really fancy graphing calculator.

Looking Things Up
-----------------
By far the most important skill you can learn here is how to Google things. When you google something like:
> how to make histogram in python

you'll usually get three types of results:
 - Websites like GeeksforGeeks, Real Python, W3Schools. These are fine, but they're usually at the top because of search engine optimization, rather than their value.
 - Documentation. This comes from the website of Python or the package itself, and it'll have a .org URL. I like these the best. They tend to be thorough and precise, but sometimes they're more terse than explanations on other sites. This varies by package.
 - Forums like StackOverflow. Every programmer, from beginner to expert, spends a ton of time on StackOverflow.

-------------------
Basic Python syntax
-------------------

In [28]:
# anything after a pound sign is a comment
print("hello world")

hello world


In [2]:
print(2 + 4)
print(2 - 4)
print(2 * 4)
print(2 / 4)
print(2 ** 4)

6
-2
8
0.5
16


------------
NumPy Arrays
------------

In [3]:
import numpy as np

my_vector = np.array([1, 0, np.pi])
my_vector_na = np.array([1, 0, np.pi, np.nan])

my_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print(np.exp(1))
print(np.exp(my_vector))

2.718281828459045
[ 2.71828183  1.         23.14069263]


In [ ]:
fon = 0.5
aeb = -np.log(1 - fon)
print(aeb)

In [4]:
print(my_matrix * my_vector)

[[ 1.          0.          9.42477796]
 [ 4.          0.         18.84955592]
 [ 7.          0.         28.27433388]
 [10.          0.         37.69911184]]


In [5]:
print(np.matmul(my_matrix, my_vector))

[10.42477796 22.84955592 35.27433388 47.69911184]


In [6]:
print(my_vector.mean())
print(my_vector_na.mean())

1.3805308845299311
nan


In [7]:
print(np.mean(my_vector))
print(np.mean(my_vector_na))

1.3805308845299311
nan


In [8]:
print(np.nanmean(my_vector))
print(np.nanmean(my_vector_na))

1.3805308845299311
1.3805308845299311


--------------------
Indexing and Slicing
--------------------

In [9]:
print(my_vector[1])

0.0


In [10]:
print(my_matrix[1])

[4 5 6]


In [11]:
print(my_vector[0:2])

[1. 0.]


In [12]:
print(my_matrix[0, 0:2])

[1 2]


In [13]:
print(my_vector > 0)

[ True False  True]


In [14]:
print(my_vector[[True, False, True]])

[1.         3.14159265]


In [15]:
print(my_vector[my_vector > 0])

[1.         3.14159265]


In [23]:
print((my_vector > 0) | (my_vector == 0))

[ True  True  True]


In [24]:
print((my_vector > 0) & (my_vector == 0))

[False False False]
